language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
# command to install dependencies
install:
  - "pip install pylint"
  - "pip install coveralls"
# command to run tests
script:
  - nosetests -v --with-coverage
  - "python pylint_runner.py"
after_success:
  - coveralls
